### ISSUE TITLE
libcaffeconverter import error

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [onnx/onnx-docker#33]
HI! I watched the tutorial, on it installed windows and one coremltools/onnxmltools. However, when you run the example, it take me error:
```
from ... import libcaffeconverter
ImportError: cannot import name 'libcaffeconverter'
```

**Comment by vinitra** [comment]
Hi @Yrij-Zhavoronkov, thanks for trying ONNX. We don't reference or depend on the libcaffeconverter in our examples -- can you link me to the document you are referring to?

You might find the caffe -> onnx conversion tutorial useful: https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/caffe_coreml_onnx.ipynb

**Comment by matherium-repo** [comment]
Hi @vinitra I'm using the tutorial you linked in your comment and I get the same error. It's because the coremltools/converters/_cafe_converter.convert() method tries to import libcaffeconverter from coremltools. 

I notice that the coremltools library directory doesn't have libcaffeconverter. Could you look into this?

**Comment by sid0913** [comment]
Same here
