### ISSUE TITLE
lightgbm prediction varies very slightly as other model don't?

### ISSUE THREAD

**Issue by hanzigs** [onnx/onnx-docker#55]
I have a lightgbm classifier, 

the model predict_proba returns
```
{"0": "0.0003362529475889886", "1": "0.999663747052411"}
```

with ONNX model
```
#saving model
initial_type = [('float_input', FloatTensorType([1, input_shape]))]
onnx_model = convert_lightgbm(lgbmmodel, initial_types=initial_type) 
with open('lgbmONNX.onnx', "wb") as f: f.write(onnx_model.SerializeToString())
content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
output_proba_name = sess.get_outputs()[1].name
```
prediction on that
```
#prediction
ONNXContent = lgbmONNX.SerializeToString()
ONNXSess = onnxruntime.InferenceSession(ONNXContent)
OnnxPrediction = ONNXSess.run([label_name, output_proba_name], {input_name: PayLoad}) 
OnnxPrediction
[array([1], dtype=int64), [{0: 0.0003362894058227539, 1: 0.9996637105941772}]]
```
not concerned about the decimal variation, just to confirm the steps are right, Thanks

**Comment by xadupre** [comment]
Your example is right. The output type for the probabilities is a dictionary by default but there is a way to keep a matrix by using option zipmap (http://onnx.ai/sklearn-onnx/auto_tutorial/plot_dbegin_options.html#option-zipmap). The converted model is then faster as the conversion from matrix to dictionary is skipped. About the discrepencies, this kind of small discrepancies is usually due to the use of float/double. The onnx model is using only float. LightGBM is using double and float. I hope that answers your question.

**Comment by hanzigs** [comment]
Thank You very much
